#!/usr/bin/bash
# shellcheck disable=SC2034

#    Copyright (c) 2022 @grm34 Neternels Team
#
#    Permission is hereby granted, free of charge, to any person
#    obtaining a copy of this software and associated documentation
#    files (the "Software"), to deal in the Software without restriction,
#    including without limitation the rights to use, copy, modify, merge,
#    publish, distribute, sublicense, and/or sell copies of the Software,
#    and to permit persons to whom the Software is furnished to do so,
#    subject to the following conditions:
#
#    The above copyright notice and this permission notice shall be
#    included in all copies or substantial portions of the Software.
#
#    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
#    EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
#    MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#    IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
#    CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
#    TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
#    SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.


## GENERAL OPTIONS
## ===============

# TimeZone (used to set build date)
# ---------------------------------
TIMEZONE="Europe/Paris"

# Device codename (e.q. X00TD)
# Info: will be prompted when set to default
# ------------------------------------------
CODENAME="default"

# Builder name (displayed in proc/version)
# Info: WHOAMI will be used when set to default
# ---------------------------------------------
BUILDER="default"

# Builder host (displayed in proc/version)
# Info: HOSTNAME will be used when set to default
# -----------------------------------------------
HOST="default"

# Default toolchain compiler
# Toolchains: Proton-Clang | Eva-GCC | Proton-GCC
# -----------------------------------------------
DEFAULT_COMPILER="Proton-Clang"

# Android kernel directory
# Tip: use TAB key for autocompletion
# Info: will be prompted when set to default
# ------------------------------------------
KERNEL_DIR="default"

# Target architecture
# -------------------
ARCH="arm64"

# Android global version
# Info: could be required by some kernels
# ---------------------------------------
PLATFORM_VERSION="12"
ANDROID_MAJOR_VERSION="s"

# Kernel variant
# --------------
KERNEL_VARIANT="Nethunter"

# Kernel name
# -----------
TAG="Neternels"

# Telegram API configuration
# Note: who the f* wants RT build status in TG?
# ---------------------------------------------
TELEGRAM_CHAT_ID=""
TELEGRAM_BOT_TOKEN=""


## ADVANCED OPTIONS (do not edit when not sure)
## ============================================

# Some required dependencies
# --------------------------
DEPENDENCIES=(wget git zip llvm lld clang expect)

# Neternels Builder branch
# ------------------------
NB_BRANCH="main"

# AnyKernel config
# ----------------
ANYKERNEL_DIR="AnyKernel"
ANYKERNEL_URL="https://github.com/grm34/AnyKernel3.git"
ANYKERNEL_BRANCH="Neternels-Builder"

# Proton-Clang config
# -------------------
PROTON_DIR="toolchains/proton_clang"
PROTON_URL="https://github.com/kdrag0n/proton-clang.git"
PROTON_BRANCH="master"

# GCC ARM64 config
# ----------------
GCC_ARM64_DIR="toolchains/gcc_arm64"
GCC_ARM64_URL="https://github.com/mvaisakh/gcc-arm64.git"
GCC_ARM64_BRANCH="gcc-master"

# GCC ARM config
# --------------
GCC_ARM_DIR="toolchains/gcc_arm"
GCC_ARM_URL="https://github.com/mvaisakh/gcc-arm.git"
GCC_ARM_BRANCH="gcc-master"

# Link Time Optimization (LTO)
# ----------------------------
LTO=False
LTO_LIBRARY=ld.lld
LTO_LIBRARY_DIR=${PROTON_DIR}/lib

# Kernel init.spectrum.rc
# -----------------------
SPECTRUM="init.spectrum.rc"

# Proton-Clang parameters
# -----------------------
PROTON_CLANG_PALTH=${PROTON_DIR}/bin
PROTON_CLANG_PARAMETERS=(
    ARCH=arm64
    SUBARCH=arm64
    CROSS_COMPILE=aarch64-linux-gnu-
    CROSS_COMPILE_ARM32=arm-linux-gnueabi-
    CC=clang
    AR=llvm-ar
    NM=llvm-nm
    OBJCOPY=llvm-objcopy
    OBJDUMP=llvm-objdump
    STRIP=llvm-strip
)

# Eva-GCC parameters
# ------------------
EVA_GCC_PATH=${GCC_ARM64_DIR}/bin:${GCC_ARM_DIR}/bin
EVA_GCC_PARAMETERS=(
    ARCH=arm64
    SUBARCH=arm64
    CROSS_COMPILE_ARM32=arm-eabi-
    CROSS_COMPILE=aarch64-elf-
    AR=aarch64-elf-ar
    OBJDUMP=aarch64-elf-objdump
    STRIP=aarch64-elf-strip
)

# Proton-GCC parameters
# ---------------------
PROTON_GCC_PATH=${PROTON_DIR}/bin:${GCC_ARM64_DIR}/bin:${GCC_ARM_DIR}/bin
PROTON_GCC_PARAMETERS=(
    ARCH=arm64
    SUBARCH=arm64
    CC=clang
    CROSS_COMPILE=aarch64-linux-gnu-
    CROSS_COMPILE_ARM32=arm-linux-gnueabi-
    AR=llvm-ar
    AS=llvm-as
    NM=llvm-nm
    STRIP=llvm-strip
    OBJCOPY=llvm-objcopy
    OBJDUMP=llvm-objdump
    OBJSIZE=llvm-size
    READELF=llvm-readelf
    HOSTCC=clang
    HOSTCXX=clang++
    HOSTAR=llvm-ar
    CLANG_TRIPLE=aarch64-linux-gnu-
)

# Excluded variables from logs
# ----------------------------
EXCLUDE_VARS="RED=\|GREEN=\|YELLOW=\|BLUE=\|CYAN=\|BOLD=\|NC=\|\
TELEGRAM_ID=\|TELEGRAM_TOKEN=\|TELEGRAM_BOT\|API=\|CONFIRM\|COUNT=\|\
LENTH=\|NUMBER=\|BASH_ARGC=\|BASH_REMATCH=\|CHAR=\|COLUMNS=\|LINES=\|\
PIPESTATUS=\|TIME=\|QUESTION=\|OPTION=\|ENTRY=\|FOLDERS=\|FOLDER=\|\
BASH_LINENO=\|BASH_SOURCE=\|STATUS_MSG=\|MSG=\|M=\|S=\|BN="
