#!/usr/bin/bash
# shellcheck disable=SC1091

#    Copyright (c) 2022 @grm34 Neternels Team
#
#    Permission is hereby granted, free of charge, to any person
#    obtaining a copy of this software and associated documentation
#    files (the "Software"), to deal in the Software without restriction,
#    including without limitation the rights to use, copy, modify, merge,
#    publish, distribute, sublicense, and/or sell copies of the Software,
#    and to permit persons to whom the Software is furnished to do so,
#    subject to the following conditions:
#
#    The above copyright notice and this permission notice shall be
#    included in all copies or substantial portions of the Software.
#
#    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
#    EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
#    MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#    IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
#    CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
#    TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
#    SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

# Enable job control
DIRNAME=$(dirname "${0}")
DIR=${PWD}/${DIRNAME}
set > "${DIR}/bashvar"
set -m -E -o pipefail

# Load configuration
source "${DIR}/config"

# Load libraries
source "${DIR}/lib/manager.sh"
source "${DIR}/lib/requirements.sh"
source "${DIR}/lib/telegram.sh"
source "${DIR}/lib/flasher.sh"
source "${DIR}/lib/maker.sh"
source "${DIR}/lib/prompter.sh"
source "${DIR}/lib/updater.sh"

# Ban all n00bz
if [[ $(uname) != Linux ]]; then
    _error "run this script on Linux !"
    _exit
elif [[ ! -f ${PWD}/config ]] || [[ ! -f ${PWD}/lib/maker.sh ]]; then
    _error "run this script from Neternels-Builder folder !"
    _exit
elif [[ $KERNEL_DIR != default  ]] && \
        [[ ! -f $KERNEL_DIR/Makefile ]]; then
    _error "you must specify a valid kernel path in config file !"
    _exit
fi

# Transform long opts to short
for OPT in "${@}"; do
    shift
    case ${OPT} in
        "--help") set -- "${@}" "-h"; break;;
        "--update") set -- "${@}" "-u";;
        "--msg") set -- "${@}" "-m";;
        "--file") set -- "${@}" "-f";;
        "--zip") set -- "${@}" "-z";;
        *) set -- "${@}" "${OPT}"
    esac
done

# Handle opts
while getopts ':hum:f:z:' OPTION; do
    case ${OPTION} in
        h)  _banner; _usage; rm "./bashvar"; exit 0;;
        u)  _full_upgrade; _exit;;
        m)  _send_msg_option; _exit;;
        f)  _send_file_option; _exit;;
        z)  _create_zip_option; _exit;;
        :)  _error "missing argument for -${OPTARG} !"; _exit;;
        \?) _error "invalid option -${OPTARG} !"; _exit
    esac
done

# Remove opts from positional parameters
shift $(( OPTIND - 1 ))

# Start new build
_banner
DATE=$(TZ=${TIMEZONE} date +%Y-%m-%d)
_note "Starting new kernel build on ${DATE} (...)"

# Get device codename
_ask_for_codename

# Create device folders
FOLDERS=(builds logs toolchains out)
for FOLDER in "${FOLDERS[@]}"; do
    if [[ ! -d ${DIR}/${FOLDER}/${CODENAME} ]] && \
            [[ ${FOLDER} != toolchains ]]; then
        mkdir -p "${DIR}/${FOLDER}/${CODENAME}"
    elif [[ ! -d ${DIR}/${FOLDER} ]]; then
        mkdir "${DIR}/${FOLDER}"
    fi
done

# Export working folders
export OUT_DIR=${DIR}/out/${CODENAME}
export BUILD_DIR=${DIR}/builds/${CODENAME}

# Trapping bash signals
trap '_error "keyboard interrupt !"; _exit' INT QUIT TSTP
trap '_notify_error; _exit' ERR

# Get user configuration
_ask_for_kernel_dir
_ask_for_defconfig
_ask_for_menuconfig
_ask_for_toolchain
_ask_for_cores

# Install and clone requirements
_install_dependencies
_clone_toolchains
_clone_anykernel

# Export target variables
if [[ ${BUILDER} == default ]]; then BUILDER=$(whoami); fi
if [[ ${HOST} == default ]]; then HOST=$(uname -n); fi
export KBUILD_BUILD_USER=${BUILDER}
export KBUILD_BUILD_HOST=${HOST}
export PLATFORM_VERSION=${PLATFORM_VERSION}
export ANDROID_MAJOR_RELEASE=${ANDROID_MAJOR_RELEASE}

# Make kernel version
_note "Make kernel version..."
make -C "${KERNEL_DIR}" kernelversion | \
    grep -v make > linuxver & wait ${!}
LINUX_VERSION=$(cat linuxver)
BUILD_NAME=${TAG}-${CODENAME}-${LINUX_VERSION}

# Telegram status msg
STATUS_MSG="

<b>Android Device :</b>  <code>${CODENAME/_/-}</code>
<b>Kernel Version :</b>  <code>v${LINUX_VERSION/_/-}</code>
<b>Kernel Variant :</b>  <code>${KERNEL_VARIANT/_/-}</code>
<b>Host Builder :</b>  <code>${BUILDER/_/-}</code>
<b>Host Core Count :</b>  <code>${CORES}</code>
<b>Compiler Used :</b>  <code>${COMPILER/_/-}</code>
<b>Operating System :</b>  <code>${HOST/_/-}</code>
<b>Build Tag :</b>  <code>${TAG/_/-}</code>
<b>Android :</b>  <code>${PLATFORM_VERSION/_/-}</code>"

# Make clean
_ask_for_make_clean
if [[ ${MAKE_CLEAN} == True ]]; then
    _make_clean & wait ${!}
fi

# Clean AnyKernel
_clean_anykernel

# Make defconfig
_make_defconfig & wait ${!}

# Make menuconfig
if [[ ${MENUCONFIG} == True ]]; then
    _make_menuconfig
    _ask_for_save_defconfig
    if [[ ${SAVE_DEFCONFIG} == True ]]; then
        _save_defconfig
    else
        if [[ ${ORIGINAL_DEFCONFIG} == False ]]; then
            _note "Build cancelled: ${BUILD_NAME}..."
            _exit
        fi
    fi
fi

# Make new build
_ask_for_new_build
if [[ ${NEW_BUILD} == False ]]; then
    _note "Build cancelled: ${BUILD_NAME}..."
    _exit
else
    # Build status ?
    _ask_for_telegram

    # Build logs
    TIME=$(TZ=${TIMEZONE} date +%H-%M-%S)
    START_TIME=$(TZ=${TIMEZONE} date +%s)
    LOG=${DIR}/logs/${CODENAME}/${CODENAME}_${DATE}_${TIME}.log

    # Make kernel
    _make_build | tee -a "${LOG}" & wait ${!}
fi

# Get build time
END_TIME=$(TZ=${TIMEZONE} date +%s)
BUILD_TIME=$((END_TIME - START_TIME))

# Display build status on TERM
M=$((BUILD_TIME / 60))
S=$((BUILD_TIME % 60))
SUCCESS="Successfully compiled after ${M} minutes and ${S} seconds"
MSG="<b>${SUCCESS}</b> ${STATUS_MSG}"
_note "${SUCCESS}"

# Send build status on Telegram
if [[ ${BUILD_STATUS} == True ]]; then
    _send_msg "${MSG}"
fi

# Create and sign flashable zip
_ask_for_flashable_zip
if [[ ${FLASH_ZIP} == True ]]; then
    _create_flashable_zip | tee -a "${LOG}"
    _sign_flashable_zip | tee -a "${LOG}"
fi

# Upload build and say goodbye
_upload_build_on_telegram
_clean_anykernel
_goodbye_msg
_exit
